---
title: "R Notebook"
output: html_notebook
---

```{r}
g <- igraph::read_graph(file = '/Users/huubvandevoort/Desktop/SNA4DS/6. Project/SNA4DS/data_preparation/prepared_data/network.graphml',
                   format = 'graphml')
```


```{r}

```


```{r}
snafun::plot_centralities(g,
                          measures = "degree",
                          mode = 'out',
                          rescaled = FALSE)
```
```{r}
degree_dist_in <- snafun::g_degree_distribution(g, mode = "in",
                              type = "count",
                              cumulative = FALSE, 
                              loops = FALSE,
                              digits = 3)
degree_dist_out <- snafun::g_degree_distribution(g, mode = "out",
                              type = "count",
                              cumulative = FALSE, 
                              loops = FALSE,
                              digits = 3)

degree_dist_all <- snafun::g_degree_distribution(g, mode = "all",
                              type = "count",
                              cumulative = FALSE, 
                              loops = FALSE,
                              digits = 3)

hist(degree_dist_in[degree_dist_in < 10],
     breaks = 10)

hist(degree_dist_out[degree_dist_out < 10],
     breaks = 10)

hist(degree_dist_all[1 < degree_dist_all],
     breaks = 150)


```


